apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskprocesserapi
spec:
  selector:
    matchLabels:
      app: taskprocesserapi
  template:
    metadata:
      labels:
        app: taskprocesserapi
    spec:
      containers:
      - name: taskprocesserapi
        image: saguhildon/taskprocesserapi:2.2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
            memory: "64Mi"        
        ports:
          - containerPort: 80
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"

---
apiVersion: v1
kind: Service
metadata:
  name: taskprocesserapi
spec:
  selector:
    app: taskprocesserapi
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taskprocesserapi-deploy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskprocesserapi
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85